# Funding links
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [miccy]
# ko_fi: your_username
# patreon: your_username
# open_collective: your_username
