name: 'Snake Evolution'
description: 'Generate an animated snake eating your GitHub contributions'
author: 'miccy'
branding:
  icon: 'activity'
  color: 'green'

inputs:
  github_user_name:
    description: 'GitHub username to generate snake for'
    required: true

  github_token:
    description: 'GitHub token for API access (optional, uses public scraping if not provided)'
    required: false
    default: ''

  outputs:
    description: 'Output file path(s), comma-separated for multiple formats'
    required: false
    default: 'dist/snake.svg'

  theme:
    description: 'Color theme (github-light, github-dark, ocean, sunset, neon-gamer, cypherpunk)'
    required: false
    default: 'github-dark'

  year:
    description: 'Year to generate contributions for'
    required: false
    default: ''  # Current year if empty

outputs:
  svg_path:
    description: 'Path to generated SVG file'
    value: ${{ steps.generate.outputs.svg_path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.4

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        bun install --frozen-lockfile

    - name: Generate Snake
      id: generate
      shell: bash
      run: |
        # Parse inputs
        OUTPUT="${{ inputs.outputs }}"
        THEME="${{ inputs.theme }}"
        YEAR="${{ inputs.year }}"
        USERNAME="${{ inputs.github_user_name }}"
        TOKEN="${{ inputs.github_token }}"
        ACTION_PATH="${{ github.action_path }}"
        WORKSPACE="${{ github.workspace }}"

        # Build output path (relative to workspace, not action path)
        OUTPUT_PATH="${WORKSPACE}/${OUTPUT}"

        # Build command (run from action path, output to workspace)
        CMD="bun run ${ACTION_PATH}/packages/cli/src/index.ts generate -u $USERNAME -t $THEME -o $OUTPUT_PATH"

        if [ -n "$YEAR" ]; then
          CMD="$CMD -y $YEAR"
        fi

        if [ -n "$TOKEN" ]; then
          CMD="$CMD --token $TOKEN"
        fi

        # Run generation
        echo "Running: $CMD"
        eval $CMD

        # Set output (relative path for user convenience)
        echo "svg_path=$OUTPUT" >> $GITHUB_OUTPUT
